CREATE TYPE INGREDIENT_TYPE AS ENUM ('VEGETABLE','ANIMAL','MARINE','DAIRY','OTHER');

CREATE TABLE INGREDIENT (
    ID int PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PRICE NUMERIC(6,2),
    CATEGORY INGREDIENT_TYPE
);

CREATE TYPE DISH_TYPE AS ENUM ('START','MAIN','DESSERT');

CREATE TABLE DISH (
    ID int PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DISH_TYPE DISH_TYPE
    id_dish int
);
